-- faction: 2 inserts, 89 updates, 0 deletes
DELETE FROM `faction` WHERE `id` IN (@WorgenPlayer, @WorgenFaction);
INSERT INTO `faction` (`id`, `reputation_index`, `reputation_race_mask_1`, `reputation_race_mask_2`, `reputation_race_mask_3`, `reputation_race_mask_4`, `reputation_class_mask_1`, `reputation_class_mask_2`, `reputation_class_mask_3`, `reputation_class_mask_4`, `reputation_base_1`, `reputation_base_2`, `reputation_base_3`, `reputation_base_4`, `reputation_flags_1`, `reputation_flags_2`, `reputation_flags_3`, `reputation_flags_4`, `parent_faction_id`, `parent_faction_mod_1`, `parent_faction_mod_2`, `parent_faction_cap_1`, `parent_faction_cap_2`, `name_enus`, `name_kokr`, `name_frfr`, `name_dede`, `name_zhcn`, `name_zhtw`, `name_eses`, `name_esmx`, `name_ruru`, `name_jajp`, `name_ptpt`, `name_itit`, `name_unused_1`, `name_unused_2`, `name_unused_3`, `name_unused_4`, `name_flags`, `description_enus`, `description_kokr`, `description_frfr`, `description_dede`, `description_zhcn`, `description_zhtw`, `description_eses`, `description_esmx`, `description_ruru`, `description_jajp`, `description_ptpt`, `description_itit`, `description_unused_1`, `description_unused_2`, `description_unused_3`, `description_unused_4`, `description_flags`) VALUES
(@WorgenPlayer, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '1.0000000000000000', '1.0000000000000000', 5, 5, '"PLAYER"," Worgen"', '', '플레이어 - 늑대인간', '"JOUEUR"," Worgen"', '"SPIELER"," Worgen"', '', '狼人(玩家)', '', '', '"JUGADOR"," Huargen"', '"JUGADOR"," Huargen"', 'ИГРОК: ворген', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188),
(@WorgenFaction, @WorgenFactionRepIndex, @AllianceMask & ~@WorgenMask, @HordeMask, @WorgenMask, 0, 0, 0, 0, 0, 3100, -42000, 4000, 0, 273, 6, 17, 0, 469, '1.0000000000000000', '0.2500000000000000', 7, 5, 'Gilneas', '길니아스', 'Gilnéas', 'Gilneas', '吉尔尼斯', '吉爾尼斯', 'Gilneas', 'Gilneas', 'Гилнеас', '', '', '', '', '', '', '', 16712190, 'The kingdom of Gilneas.', '길니아스 왕국입니다.', 'Le royaume de Gilnéas.', 'Das Königreich Gilneas.', '吉尔尼斯王国。', '吉爾尼斯王國。', 'El reino de Gilneas.', 'El reino de Gilneas.', 'Королевство Гилнеас.', '', '', '', '', '', '', '', 16712190);
/*
-- Changed values
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 21;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 46;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 47;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 54;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 59;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 67;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 68;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 69;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 70;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 72;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 76;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 81;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 83;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 86;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 87;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 92;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 93;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 169;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 270;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 289;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 349;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 369;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 469;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 470;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 471;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 509;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 510;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 529;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 530;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 549;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 550;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 551;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 569;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 570;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 571;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 574;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 576;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 577;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 589;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 609;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 729;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 730;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 749;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 809;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 889;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 890;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 891;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 892;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 909;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 910;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 911;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 922;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 930;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 932;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 933;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 934;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 935;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 936;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 941;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 942;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 946;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 947;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 970;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 978;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 989;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 990;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1012;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1015;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1031;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1037;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1038;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1050;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 1052;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 1064;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 1067;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1068;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1073;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1082;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1085;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask, `reputation_race_mask_3` = `reputation_race_mask_3` | @WorgenMask WHERE `id` = 1090;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1091;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1094;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1104;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1105;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1117;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1118;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1119;
UPDATE `faction` SET `reputation_race_mask_2` = `reputation_race_mask_2` | @WorgenMask WHERE `id` = 1124;
UPDATE `faction` SET `reputation_race_mask_1` = `reputation_race_mask_1` | @WorgenMask WHERE `id` = 1126;
*/